package com.niuran.giftstore.dao;

import com.niuran.giftstore.model.CartDetail;
import com.niuran.giftstore.model.CartDetailExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CartDetailMapper {
    int countByExample(CartDetailExample example);

    int deleteByExample(CartDetailExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CartDetail record);

    @Options(useGeneratedKeys = true)
    int insertSelective(CartDetail record);

    List<CartDetail> selectByExample(CartDetailExample example);

    CartDetail selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CartDetail record, @Param("example") CartDetailExample example);

    int updateByExample(@Param("record") CartDetail record, @Param("example") CartDetailExample example);

    int updateByPrimaryKeySelective(CartDetail record);

    int updateByPrimaryKey(CartDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CartDetail selectOneByExample(CartDetailExample example);
}