package com.niuran.giftstore.dao;

import com.niuran.giftstore.model.GiftSnapshot;
import com.niuran.giftstore.model.GiftSnapshotExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GiftSnapshotMapper {
    int countByExample(GiftSnapshotExample example);

    int deleteByExample(GiftSnapshotExample example);

    int deleteByPrimaryKey(Long id);

    int insert(GiftSnapshot record);

    @Options(useGeneratedKeys = true)
    int insertSelective(GiftSnapshot record);

    List<GiftSnapshot> selectByExample(GiftSnapshotExample example);

    GiftSnapshot selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") GiftSnapshot record, @Param("example") GiftSnapshotExample example);

    int updateByExample(@Param("record") GiftSnapshot record, @Param("example") GiftSnapshotExample example);

    int updateByPrimaryKeySelective(GiftSnapshot record);

    int updateByPrimaryKey(GiftSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_snapshot
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GiftSnapshot selectOneByExample(GiftSnapshotExample example);
}