package com.niuran.giftstore.dao;

import com.niuran.giftstore.model.GiftActionRecord;
import com.niuran.giftstore.model.GiftActionRecordExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GiftActionRecordMapper {
    int countByExample(GiftActionRecordExample example);

    int deleteByExample(GiftActionRecordExample example);

    int deleteByPrimaryKey(Long id);

    int insert(GiftActionRecord record);

    @Options(useGeneratedKeys = true)
    int insertSelective(GiftActionRecord record);

    List<GiftActionRecord> selectByExample(GiftActionRecordExample example);

    GiftActionRecord selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") GiftActionRecord record, @Param("example") GiftActionRecordExample example);

    int updateByExample(@Param("record") GiftActionRecord record, @Param("example") GiftActionRecordExample example);

    int updateByPrimaryKeySelective(GiftActionRecord record);

    int updateByPrimaryKey(GiftActionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_action_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GiftActionRecord selectOneByExample(GiftActionRecordExample example);
}