package com.niuran.giftstore.dao;

import com.niuran.giftstore.model.TheOrder;
import com.niuran.giftstore.model.TheOrderExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TheOrderMapper {
    int countByExample(TheOrderExample example);

    int deleteByExample(TheOrderExample example);

    int deleteByPrimaryKey(Long id);

    int insert(TheOrder record);

    @Options(useGeneratedKeys = true)
    int insertSelective(TheOrder record);

    List<TheOrder> selectByExample(TheOrderExample example);

    TheOrder selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") TheOrder record, @Param("example") TheOrderExample example);

    int updateByExample(@Param("record") TheOrder record, @Param("example") TheOrderExample example);

    int updateByPrimaryKeySelective(TheOrder record);

    int updateByPrimaryKey(TheOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table the_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TheOrder selectOneByExample(TheOrderExample example);
}